# Generated by Django 3.2.5 on 2021-07-26 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0002_alter_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
