# Generated by Django 3.2.5 on 2021-07-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0005_auto_20210726_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighborhood',
            old_name='health_tell',
            new_name='hospital_number',
        ),
    ]
