# Generated by Django 3.2.5 on 2021-07-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0006_rename_health_tell_neighborhood_hospital_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='hospital_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='police_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
