# Generated by Django 3.2.5 on 2021-07-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0007_auto_20210726_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='hospital_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='police_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
