# Generated by Django 3.2.5 on 2021-07-26 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0008_auto_20210726_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
