# Generated by Django 3.2.5 on 2021-07-26 23:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0009_remove_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='bs_image',
            field=cloudinary.models.CloudinaryField(default='image/upload/v1627341811/company_default_qb4ili.png', max_length=255, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='image/upload/v1626430054/default_zogkvr.png', max_length=255, verbose_name='image'),
        ),
    ]
