# Generated by Django 3.2.5 on 2021-07-26 23:45

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0010_auto_20210727_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='hood_pic',
            field=cloudinary.models.CloudinaryField(default='image/upload/v1627343010/neighborhood1_cj2fyx.jpg', max_length=255, verbose_name='images'),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='hospital_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='police_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='police_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
