# Generated by Django 3.2.5 on 2021-07-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0011_auto_20210727_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='manager_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='manager_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='manager_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
