# Generated by Django 3.2.5 on 2021-07-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0012_auto_20210727_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='close_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='business',
            name='open_time',
            field=models.CharField(max_length=50),
        ),
    ]
